### ISSUE TITLE
Duplicate sources for android-native with flashdevelop

### ISSUE THREAD

**Issue by sh-dave** [KTXSoftware/koremake#20]
i have the problem that i get duplicate sources for android-native.
- 1) in build/android-native-build/Sources
- 2) in build/android-native-build/MYAPPNAME/app/src/main/jni/build/android-native-build/Sources

2) seems to get picked up by gradle and actually used for building
1) seems to be generated by flashdevelop

i can't just use flashdevelop now to program and have it update the sources (like in every other target), but have to run ```node Kha/make android-native``` again to get the changes.

I haven't tested if this works in intellij (using the ```project-andorid-native-intellij``` project), it may have the same problem.

**Comment by RobDangerous** [comment]
All necessary sources are copied to android-native-build/Sources (not just the cross-compiled Haxe sources). No way around it because Android Studio currently doesn't have a proper C/C++ build system.
Sorry, please forward to Google.
