### ISSUE TITLE
XCode fails if spaces in path

### ISSUE THREAD

**Issue by Nolanus** [KTXSoftware/koremake#9]
Hi,

I experienced spaces in the pathname to result in corrupted XCode project files to be created by koremake. I figured out that source of the problem are unescaped spaces and adjusted the koremake script to prevent this on OS X 10.9.5 and XCode 6.2 (and probably later version as well).
Got a [working fork of koremake](https://github.com/Nolanus/koremake/commit/ee3dfb29ee8387784ef19a90658d97bc86a90d4f), please contact me, if I should create a pull request.

Sebastian

**Comment by RobDangerous** [comment]
Hi Sebastian!

Code looks good, please create a pull request (don't want to just copy it because I very much prefer to have all contributions in the commit log).
